name: Node.js CI

on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Python deps
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Get commit hash
      id: commit_hash
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm install
    - run: npm run build --if-present
    - run: npm run test --if-present
    - name: Get New Package Version
      id: get-package-version
      uses: martinbeentjes/npm-get-version-action@master
    - name: Re-version package with commit hash for PR artifact
      run: npm version --no-git-tag-version ${{ steps.get-package-version.outputs.current-version }}-${{ steps.commit_hash.outputs.sha_short }}
    - name: Generate offline bundled package
      run: npm run pack-all
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: romi-service-${{ steps.get-package-version.outputs.current-version }}-${{ steps.commit_hash.outputs.sha_short }}.tgz
        path: wpilib-*.tgz
